config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :options

  resources :questions

  resources :assessments do
    resources :questions
  end

  resources :users, :controller => 'users' do
    collection do
      resources :assessments
    end

  end 
  
  resources :teachers do
    collection do
      get :my_students
    end
  end
  
  resources :students do
    collection do
      get :live_assessments
    end
    resources :attempt_tests
  end

  root 'welcomes#index'

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base

	has_many :questions

	has_many :attempts
	has_many :students, through: :attempts

	
	accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:text].blank? }, :allow_destroy => true
	
	validates :name, :presence => true
	validate  :date_validate

	scope :live, -> {where("? BETWEEN start_date AND end_date", Time.now.to_date)}

	def date_validate
		errors.add(:base, 'End date should be after Start date') if start_date.to_i > end_date.to_i
	end



end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]

  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = current_user.assessments
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new({user_id: current_user.id}.merge(assessment_params))

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to edit_assessment_path @assessment, notice: 'Assessment was successfully created.' }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update({user_id: current_user.id}.merge(assessment_params))
        format.html { redirect_to assessments_path, notice: 'Assessment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to assessments_url, notice: 'Assessment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assessment_params
      params.require(:assessment).permit(:name, :weight, :start_date, :end_date, {questions_attributes: [:id, :text, :rating, :_destroy]})
    end

end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_form.html.erb
<%= form_for @assessment, :html => { :class => "form-horizontal assessment" } do |f| %>

  <% if @assessment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@assessment.errors.count, "error") %> prohibited this assessment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @assessment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :weight, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :weight, :class => 'form-control' %>
    </div>
    <%=f.error_span(:weight) %>
  </div>
  <div class="form-group">
    <%= f.label :start_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.datetime_select :start_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:start_date) %>
  </div>
  <div class="form-group">
    <%= f.label :end_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.datetime_select :end_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:end_date) %>
  </div>

  <div class="pull-right">
    <% if f.object.id.present? %>   
      <%= link_to t('.new', :default => t("helpers.links.add_new_question")),
          new_assessment_question_path(f.object.id), :class => 'btn btn-default btn-xs' %>
    <% end %>
  </div>

  <br>
  <br>
  
  <%= f.fields_for :questions do |builder| %>
    <div class="form-group">
      <%= render 'question_fields', :f => builder %>
    </div>
  <% end %>

 

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                assessments_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/assessments/_question_fields.html.erb
  <%= f.label :"question", :class => 'control-label col-lg-3' %>
  
  <div class="col-lg-6">
  <div class="col-lg-1">
  </div>
  <div class="col-lg-10">
		<%= f.text_field :text, :class => 'form-control' %>
  	<%= f.hidden_field :id %>
  </div>
  </div>
		<%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_path(f.object.id), :class => 'btn btn-default btn-xs' %>
		<%= f.hidden_field :_destroy %>
  	<%= link_to "remove", '#', onclick: "remove_fields(this); return false", :class => 'btn btn-xs btn-danger' %>
		

app/views/assessments/edit.html.erb
<%- model_class = Assessment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/assessments/index.html.erb
<%- model_class = Assessment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:total_questions) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
        <td><%= link_to assessment.id, assessment_path(assessment) %></td>
        <td><%= assessment.name %></td>
        <td><%= assessment.questions.count %></td>
        <td><%= assessment.weight %></td>
        <td><%=l assessment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_assessment_path(assessment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      assessment_path(assessment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_assessment_path,
            :class => 'btn btn-primary' %>

app/views/assessments/new.html.erb
<%- model_class = Assessment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/assessments/show.html.erb
<%- model_class = Assessment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @assessment.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @assessment.weight %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              assessments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_assessment_path(@assessment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              assessment_path(@assessment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>